# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.mailgun.org:587
mail_admin: forms@marisamorby.com
mail_hostname: smtp.mailgun.org
mail_user: forms@marisamorby.com
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
